# Generated by Django 5.1.2 on 2024-10-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestScribeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('adventurer', 'Adventurer')], default='reader', max_length=10),
        ),
    ]
