# Generated by Django 5.1.2 on 2024-10-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestScribeapi', '0007_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='campaign_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='character_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='important_npcs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='inspiration_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='related_quest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='session_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
